# Generated by Django 5.0.2 on 2024-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_l3', '0002_auto_20240412_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='status_name',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('solved', 'Solved'), ('closed', 'Closed')], max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketsolutionmodel',
            name='ticket_solution_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
