# Generated by Django 5.0.2 on 2024-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_l3', '0003_alter_statusmodel_status_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsmodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
