# Generated by Django 5.0.2 on 2024-04-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_l3', '0005_ticketsolutionattachmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsmodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='app_l3/ticket_attachments/'),
        ),
    ]
